version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo-db-nequi
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: franchises_db
    volumes:
      - mongo_data:/data/db
    networks:
      - franchise-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    container_name: franchises-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/franchises_db
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - franchise-network
    restart: always

networks:
  franchise-network:
    driver: bridge

volumes:
  mongo_data: