spring:
  application:
    name: api-franquicias
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/franchises_db}

aws:
  dynamodb:
    table-name: ${DYNAMODB_TABLE_NAME:Franchises}
    region: ${AWS_REGION:us-east-1}

springdoc:
  swagger-ui:
    enabled: true
    ui-path: /swager-ui.html
  api-docs:
    enabled: true