spring:
  application:
    name: api-franquicias
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb+srv://franchises-api:ps0QDitWWEYm90Q5@cluster0.uas15dz.mongodb.net/franchises_db?retryWrites=true&w=majority&tlsAllowInvalidHostnames=true}

springdoc:
  swagger-ui:
    enabled: true
    ui-path: /swager-ui.html
  api-docs:
    enabled: true